version: "3.7"

services:

# ####################### React #########################
  ft_react:
    depends_on:
      - ft_nestjs
    build:
      context: ./front-end
    container_name: "container-front-end"
    image: img-front-end
    env_file:
      - "./.env"
    ports:
      - "8080:3000"
    networks:
      - webnet
    # volumes:
    #   - /home/mkayumba/data/database:/var/lib/mysql
    restart: always

# ####################### NestJS #########################

  ft_nestjs:
    depends_on:
      - ft_postgres
    build:
      context: ./back-end
      target: development
      # dockerfile: ./Dockerfile
    container_name: "container-nestjs"
    env_file:
      - ./.env
    networks:
      - webnet
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
       - ./back-end:/usr/src/app
       - /usr/src/app/node_modules
    command: npm run start:dev
    restart: always

# ####################### postgres #########################
  ft_postgres:
    image: postgres
    container_name: "container-postgress"
#    env_file:
#      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet
    restart: always

networks:
  webnet:
volumes:
  pgdata:
